---
title: "Load STATA May 15"
author: "Raymond R. Balise & Layla Bouzoubaa"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    df_print: kable
    toc: true
    config:
      toc:
        collapsed: 2
    toc_depth: 4
    toc_float: true
    
    theme: default
    highlight: tango
---

```{r setup, include=FALSE, message=FALSE}
library(conflicted)
suppressMessages(conflict_prefer("filter", "dplyr"))
suppressPackageStartupMessages(library(tidyverse))

library(haven)  # read_stata
library(stringi)  # stri_encode
```

# Info
Data from Touchton, Michael <miketouchton@miami.edu> Tuesday, Thursday, May 21, 2020 at 4:33 PM

## Pre-processing

## Notes:

```{r}
analysis <- read_stata("../data/Covid-19 mayo 15 (clean).dta", encoding = "latin1") %>% 
  rename(`Days Since the First Case (in Mexico)`  = Days) %>% 
  rename(`Total Cases`  = Total_Cases) %>% 
  rename(`Policy Index Adjusted for Time` = Policy_Index_Adjusted_Time) %>% 
  #rename(`Deaths/ICU Bed` = Deaths_per_ICUbed) %>% 
  #rename(`Policy Index Adj Time Mobility` = Policy_Index_Adj_Time_Mobility) %>% 
  rename(`Cases per capita` = cases_per_capita) %>% 
  rename(`Deaths per capita` = deaths_per_capita) %>%
  rename(`Mobility Index` = Mobility_Index) %>% 
  rename(`Icu_beds` = `Icubeds`) %>% 
  mutate(State_Name = stri_encode(State_Name, "latin1", "UTF-8")) %>% # accents
  mutate(`State Name` = case_when(State_Name == "MichoacÂ‡n" ~ "Michoacán",
                                State_Name == "Nuevo LeÂ—n" ~ "Nuevo León",
                                State_Name == "QuerÂŽtaro" ~"Querétaro",
                                State_Name == "San Luis PotosÂ’" ~ "San Luis Potosí",
                                State_Name == "YucatÂ‡n" ~ "Yucatán",
                                State_Name == "Mex" ~ "Estado de México",
                                State_Name == "Ciudad de Mexico" ~ "Ciudad de México",
                                TRUE ~ State_Name)) %>% 
  mutate(`Mobility Index` = case_when(`Days Since the First Case (in Mexico)` == 79 ~ NA_real_,
                                         TRUE ~ `Mobility Index`))

write_rds(analysis, "../data/analysis.rds")

```


