---
title: "Load STATA"
author: "Raymond R. Balise"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    df_print: kable
    toc: true
    config:
      toc:
        collapsed: 2
    toc_depth: 4
    toc_float: true
    
    theme: default
    highlight: tango
---

```{r setup, include=FALSE, message=FALSE}
library(conflicted)
suppressMessages(conflict_prefer("filter", "dplyr"))
suppressPackageStartupMessages(library(tidyverse))

library(haven)  # read_stata
library(stringi)  # stri_encode
```

# Info
Data from Touchton, Michael <miketouchton@miami.edu> Saturday, Sunday, April 19, 2020 at 10:24 AM  Stacked data in Stata

## Pre-processing

## Notes:
Written approval to put sheets on web is pending

```{r}
analysis <- read_stata("../data/covid-19 abril 27.dta", encoding = "latin1") %>% 
  rename(`Days Since the First Case (in Mexico)`  = Days) %>% 
  rename(`Total Cases`  = Total_Cases) %>% 
  rename(`Policy Index Adjusted for Time` = Policy_Index_Adjusted_Time) %>% 
  #rename(`Deaths/ICU Bed` = Deaths_per_ICUbed) %>% 
  rename(`Policy Index Adj Time Mobility` = Policy_Index_Adj_Time_Mobility) %>% 
  rename(`Cases per capita` = cases_per_capita) %>% 
  rename(`Deaths per capita` = deaths_per_capita) %>%
  rename(`Mobility Index` = Mobility_Index) %>% 
  mutate(State_Name = stri_encode(State_Name, "latin1", "UTF-8")) %>% # accents
  mutate(`State Name` = case_when(State_Name == "Michoac‡n" ~ "Michoacan",
                                State_Name == "Nuevo Le—n" ~ "Nuevo Leon",
                                State_Name == "QuerŽtaro" ~"Queretaro",
                                State_Name == "San Luis Potos’" ~ "San Luis Potosi",
                                State_Name == "Yucat‡n" ~ "Yucatan",
                                TRUE ~ State_Name))

write_rds(analysis, "../data/analysis.rds")

```


