---
title: "Polar Plot "
author: "Raymond R. Balise"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: kable
    toc: false
---

```{r setup, include=FALSE, message=FALSE}
library(conflicted)
suppressMessages(conflict_prefer("filter", "dplyr"))
suppressPackageStartupMessages(library(tidyverse))
library(readr)

```

# Info


## Notes:
```{r}
knitr::opts_chunk$set(fig.width=24, fig.height=16) 

library(viridis)
library(ggthemes)


mexico <- read_rds("../data/analysis.rds")
latest <- max(mexico[ "Days Since the First Case (in Mexico)"])

spider <- function(day) {

polar <- mexico %>% 
  filter(`Days Since the First Case (in Mexico)`== day) %>% 
#  filter(`State Name` == "Mex") %>% 
  select(`State Name`, School_Closure,
         Workplace_Closure,
         Public_Events_Cancelled,
         Public_Transit_Suspended,
         Information_Campaign,
         Internal_Travel_Control,
         International_Travel_Controls) %>% 
  pivot_longer(-`State Name`, names_to = "Restriction", values_to = "amount") %>% 
  mutate(Restriction = case_when(Restriction == "Workplace_Closure" ~              "  Área\nlaboral  ",
                                 Restriction == "Information_Campaign" ~          "   Campaña\ninformativa",
                                 Restriction == "Internal_Travel_Control" ~       " Viajes\n    domésticos",
                                 Restriction == "International_Travel_Controls" ~ " Viajes\n inter.",
                                 Restriction == "Public_Events_Cancelled" ~       " Eventos\npúblicos", 
                                 Restriction == "Public_Transit_Suspended" ~      " Transporte\npúblico",
                                 Restriction == "School_Closure" ~                "Cierre\nde escuelas"))





polar  %>%  
#filter(`State Name` == "Aguascalientes") %>% 
ggplot(aes(x = Restriction, ymax=amount, ymin = 0)) +
  geom_hline(yintercept = .5, color = "lightgray") +
  #geom_hline(yintercept = 1, color = "darkgray") +
  geom_linerange(aes(ymax = .95), stat = "identity", color = "white") +
	geom_linerange(aes(color = "red"), stat = "identity",  size  = 2) +
	theme_gray(base_size = 15) +
	theme(panel.border = element_blank(),
				legend.key = element_blank(),
				axis.ticks = element_blank(),
				axis.text.y = element_blank(),
				panel.grid  = element_blank(),
				axis.title = element_blank() ,
				legend.position = "none"
				) +
  #scale_color_viridis(end = .6, option = "B") +

  scale_y_continuous(expand = c(0,0), limits = c(0, 1.1)) +
  facet_wrap(vars(`State Name`)) +
	coord_polar(theta = "x") -> gg



# #base 100 height 12000
# # base 15 1800
# polar  %>%  
# #  filter(`State Name` == "Aguascalientes") %>% 
# ggplot(aes(x = Restriction, ymax=amount, ymin = 0, fill = Restriction)) +
#   geom_linerange(aes(ymax = .95), stat = "identity", color = "white") +
# 	geom_linerange(aes(color = amount), stat = "identity",  size  = 2) +
# 	theme_gray(base_size = 15) +
# 	theme(panel.border = element_blank(),
# 				legend.key = element_blank(),
# 				axis.ticks = element_blank(),
# 				axis.text.y = element_blank(),
# 				panel.grid  = element_blank(),
# 				axis.title = element_blank() ,
# 				legend.position = "none"
# 				) +
#   scale_color_viridis(end = .6, option = "B") +
#   scale_y_continuous(expand = c(0,0), limits = c(0, 1.1)) +  
# 
#   facet_wrap(vars(`State Name`)) +
# 	coord_polar(theta = "x") -> gg

png(filename=paste0("../www/polarBarChart", day, ".png"), width=1800, height=1800)
print(gg)
dev.off()

}

walk(1:latest, spider)

```


```{r}
knitr::opts_chunk$set(fig.width=24, fig.height=16) 

library(viridis)
library(ggthemes)


mexico <- read_rds("../data/analysis.rds")
latest <- max(mexico[ "Days Since the First Case (in Mexico)"])

polar <- mexico %>% 
  filter(`Days Since the First Case (in Mexico)`== latest) %>% 
#  filter(`State Name` == "Mex") %>% 
  select(`State Name`, School_Closure,
         Workplace_Closure,
         Public_Events_Cancelled,
         Public_Transit_Suspended,
         Information_Campaign,
         Internal_Travel_Control,
         International_Travel_Controls) %>% 
  pivot_longer(-`State Name`, names_to = "Restriction", values_to = "amount") %>% 
  mutate(Restriction = case_when(Restriction == "Workplace_Closure" ~              "  Área\nlaboral  ",
                                 Restriction == "Information_Campaign" ~          "   Campaña\ninformativa",
                                 Restriction == "Internal_Travel_Control" ~       " Viajes\n    domésticos",
                                 Restriction == "International_Travel_Controls" ~ " Viajes\n inter.",
                                 Restriction == "Public_Events_Cancelled" ~       " Eventos\npúblicos", 
                                 Restriction == "Public_Transit_Suspended" ~      " Transporte\npúblico",
                                 Restriction == "School_Closure" ~                "Cierre\nde escuelas"))


#base 100 height 12000
# base 15 1800
polar  %>%  
#  filter(`State Name` == "Aguascalientes") %>% 
ggplot(aes(x = Restriction, ymax=amount, ymin = 0, fill = Restriction)) +
  geom_linerange(aes(ymax = .95), stat = "identity", color = "white") +
	geom_linerange(aes(color = amount), stat = "identity",  size  = 2) +
	theme_gray(base_size = 15) +
	theme(panel.border = element_blank(),
				legend.key = element_blank(),
				axis.ticks = element_blank(),
				axis.text.y = element_blank(),
				panel.grid  = element_blank(),
				axis.title = element_blank() ,
				legend.position = "none"
				) +
  scale_color_viridis(end = .6, option = "B") +
  scale_y_continuous(expand = c(0,0), limits = c(0, 1.1)) +  

  facet_wrap(vars(`State Name`)) +
	coord_polar(theta = "x") -> gg

png(filename=paste0("../www/polarBarChart.png"), width=1800, height=1800)
print(gg)
dev.off()
```

Length of red line indicates restrictions.















```


