---
title: "Reference Plot "
author: "Raymond R. Balise"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    df_print: kable
    toc: true
    config:
      toc:
        collapsed: 2
    toc_depth: 4
    toc_float: true
    
    theme: default
    highlight: tango
---

```{r setup, include=FALSE, message=FALSE}
library(conflicted)
suppressMessages(conflict_prefer("filter", "dplyr"))
suppressPackageStartupMessages(library(tidyverse))

library(readxl)

library(ggthemes)
```

# Info


## Notes:


# Index
```{r makeData}
analysis <- read_rds("../data/analysis.rds") %>% 
  rename(place = `State Name`) %>% 
  arrange(place, `Days Since the First Case (in Mexico)`) %>% 
  mutate(place = factor(place)) %>% 
  mutate(place = factor(place, levels = rev(levels(place))))

ref <- analysis %>% 
  filter(place %in% c("Chiapas", "Nuevo León")) %>% 
  filter(!is.na(`Policy Index Adjusted for Time`))

place <- analysis %>% 
  filter(place %in% c("Veracruz")) %>% 
  filter(!is.na(`Policy Index Adjusted for Time`))

```


```{r plotIndex}

ggplot() + 
  theme_few(base_size = 25) +
  geom_line(data = place, 
             aes(x=`Days Since the First Case (in Mexico)`, 
                 y = `Policy Index Adjusted for Time`), color = "orange") +
  geom_line(data = ref, 
             aes(x=`Days Since the First Case (in Mexico)`, 
                 y = `Policy Index Adjusted for Time`, group = place), 
            color = "gray") +
  geom_text(data = ref, x = 45, y = 15, label = "Chiapas", color = "gray") +
  geom_text(data = ref, x = 44, y = 45, label = "Nuevo León", color = "gray") +
  ylim (0, 70)

```

# Daily Cases
```{r}
ggplot() + 
  theme_few(base_size = 25) +
  geom_point(data = place, 
             aes(x=`Days Since the First Case (in Mexico)`, 
                 y = `Daily_Cases`, group = place), 
             color = "orange") +
  geom_smooth(data = ref, 
             aes(x=`Days Since the First Case (in Mexico)`, 
                 y = `Daily_Cases`, group = place, color = place),
             method = 'loess',
             formula = 'y ~ x') 
```
